### ISSUE TITLE
Add Filter to RC roster

### ISSUE THREAD

**Issue by wismer** [recursecenter/community#301]
The roster for all current and former RC's has gotten quite large. Is there a way to filter by batch/year? If not, I think it might be a useful feature to add in the future.

**Comment by zachallaun** [comment]
Do you mean on recurse.com/people? If so, that's a different app than this repo. However, we're planning an eventual complete rewrite of that page… it's definitely too unwieldy in its current state.

I'm going to close this issue because I don't think it has to do with Community, but if I'm mistaken please reopen!

**Comment by wismer** [comment]
oh yes, you are right. my mistake!
