### ISSUE TITLE
Duplicate messages & emails

### ISSUE THREAD

**Issue by alexandrinaw** [recursecenter/community#384]
Starting a few days ago, I noticed duplicate community messages in my email. This has happened in at least two thread, from at least three different users. Upon further inspection, the duplicated messages are also on the web, but don't seem to occur for every single person who posts, just some of them. Based on the increasing amount of time between duplicated messages, I'd guess there's some exponential backoff type of thing going on where something is attempting to post the message multiple times. Based on the fact that it seems to only apply to some messages but not all, I'd guess that your email provider (mailgun?) is the thing causing the duplication, but without logs nor being fluent in ruby, that's as far as my debugging can take me.

**Comment by davidbalbert** [comment]
We looked into this on Friday and came to the same conclusion you did.

During the period that the duplicate messages were sent, we were having issues with requests to Community timing out. Our guess is that while we were successfully creating the messages in our database, we were timing out before we were able to write a response to Mailgun. Mailgun, upon receiving a 500 from us (due to the timeout) backed off and then tried again.

Given that we're no longer timing out, I'm going to close this issue. Please reopen if you notice it again.
